"""Module: communication
Description: Pydantic models for communication drafting in the VQMS pipeline.

Defines DraftEmailPackage and ValidationReport models used by the
Communication Drafting Agent (Step 9) and Quality & Governance Gate (Step 10).
"""

from __future__ import annotations

import logging
import re
from datetime import datetime
from enum import StrEnum

from pydantic import BaseModel, Field, field_validator

_TICKET_NUMBER_PATTERN = re.compile(r"^INC\d{7,10}$")

logger = logging.getLogger(__name__)


class DraftType(StrEnum):
    """Types of email drafts generated by the Communication Drafting Agent."""

    ACKNOWLEDGMENT = "acknowledgment"
    RESOLUTION = "resolution"
    ESCALATION_NOTICE = "escalation_notice"
    FOLLOW_UP = "follow_up"
    REOPEN_NOTICE = "reopen_notice"


class ValidationStatus(StrEnum):
    """Validation outcome from the Quality & Governance Gate."""

    PASSED = "passed"
    FAILED = "failed"
    REQUIRES_REVIEW = "requires_review"


class DraftEmailPackage(BaseModel):
    """Email draft package produced by the Communication Drafting Agent.

    Contains the generated email content along with metadata for
    the Quality & Governance Gate to validate before sending.

    Attributes:
        draft_id: Unique draft identifier.
        draft_type: Type of email being drafted.
        ticket_number: ServiceNow ticket number included in email.
        vendor_name: Recipient vendor name.
        subject: Email subject line (includes ticket number).
        body_html: HTML formatted email body.
        body_plain: Plain text fallback body.
        sla_statement: SLA statement included in the email.
        thread_headers: Email threading headers (In-Reply-To, References).
        created_at: Draft creation timestamp.
        model_id: LLM model used for generation.
        prompt_version: Prompt template version used.
        tokens_used: Total tokens consumed for generation.
        correlation_id: Tracing ID propagated through the pipeline.
    """

    draft_id: str = Field(..., description="Unique draft identifier")
    draft_type: DraftType = Field(..., description="Type of email draft")
    ticket_number: str = Field(..., description="ServiceNow ticket number")
    vendor_name: str = Field(..., description="Recipient vendor name")
    subject: str = Field(..., description="Email subject with ticket number")
    body_html: str = Field(..., description="HTML formatted email body")
    body_plain: str = Field(..., description="Plain text fallback body")
    sla_statement: str = Field(..., description="SLA statement in email")
    thread_headers: dict[str, str] = Field(
        default_factory=dict, description="Email threading headers"
    )
    created_at: datetime = Field(..., description="Draft creation timestamp")
    model_id: str = Field(..., description="LLM model used")
    prompt_version: str = Field(..., description="Prompt template version")
    tokens_used: int = Field(default=0, ge=0, description="Tokens consumed")
    correlation_id: str = Field(..., description="Pipeline correlation ID")

    @field_validator("ticket_number")
    @classmethod
    def _validate_ticket_number(cls, v: str) -> str:
        if not _TICKET_NUMBER_PATTERN.match(v):
            msg = (
                f"Invalid ticket number format: {v!r}."
                " Expected INC followed by 7-10 digits."
            )
            raise ValueError(msg)
        return v


class ValidationReport(BaseModel):
    """Validation report from the Quality & Governance Gate (Step 10).

    Maps to audit.validation_results table. Records the outcome of
    all quality checks performed on a draft email before sending.

    Attributes:
        report_id: Unique report identifier.
        draft_id: Reference to the validated draft.
        status: Overall validation outcome.
        checks: Individual check results with pass/fail and details.
        ticket_number_valid: Whether ticket number format is correct.
        sla_wording_valid: Whether SLA statement matches policy.
        template_compliant: Whether draft follows template structure.
        pii_detected: Whether PII was found in the draft.
        pii_details: Details of any PII detections.
        governance_policy_met: Whether governance policies are satisfied.
        validated_at: Validation timestamp.
        correlation_id: Tracing ID propagated through the pipeline.
    """

    report_id: str = Field(..., description="Unique report identifier")
    draft_id: str = Field(..., description="Reference to validated draft")
    status: ValidationStatus = Field(..., description="Overall validation outcome")
    checks: list[dict[str, object]] = Field(
        default_factory=list, description="Individual check results"
    )
    ticket_number_valid: bool = Field(
        default=False, description="Ticket number format valid"
    )
    sla_wording_valid: bool = Field(
        default=False, description="SLA statement matches policy"
    )
    template_compliant: bool = Field(
        default=False, description="Draft follows template"
    )
    pii_detected: bool = Field(default=False, description="PII found in draft")
    pii_details: list[str] = Field(
        default_factory=list, description="PII detection details"
    )
    governance_policy_met: bool = Field(
        default=False, description="Governance policies satisfied"
    )
    validated_at: datetime = Field(..., description="Validation timestamp")
    correlation_id: str = Field(..., description="Pipeline correlation ID")
